package-as: OctoChargeBar
ignore:
  - README.md
  - .gitignore
  - .github
  - .vscode
  - .gitattributes
  - .luacheckrc
  - Images
externals:
  lib/AceAddon-3.0:
    url: 'https://repos.wowace.com/wow/ace3/trunk/AceAddon-3.0'
    tag: latest
  lib/AceEvent-3.0:
    url: 'https://repos.wowace.com/wow/ace3/trunk/AceEvent-3.0'
    tag: latest
  lib/AceDB-3.0:
    url: 'https://repos.wowace.com/wow/ace3/trunk/AceDB-3.0'
    tag: latest
  lib/LibStub:
    url: https://repos.curseforge.com/wow/libstub/trunk
    tag: latest
  lib/LibEditMode:
    url: https://github.com/p3lim-wow/LibEditMode
    tag: latest
